version: '3'

volumes: 
    static_files:

services: 
    db:
        image: postgres:latest
        environment: 
            - POSTGRES_DB=cloud-disk-db
            - POSTGRES_PASSWORD=postgrespassword
        ports: 
            - "5432:5432"
    web:
        build: .
        command: gunicorn -w 4 CloudDisk.wsgi -b 0.0.0.0:8000
        ports: 
            - "8000:8000"
        depends_on: 
            - db
        environment: 
            AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
            AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
            AWS_STORAGE_BUCKET_NAME: "${AWS_STORAGE_BUCKET_NAME}"
        volumes: 
            - static_files:/static_files
    nginx:
        build: 
            context: .
            dockerfile: nginx/Dockerfile
        ports: 
            - "8080:80"
        depends_on: 
            - web
        volumes: 
            - static_files:/static_files