version: '3'

services: 
    db:
        image: postgres:latest
        environment: 
            - POSTGRES_DB=cloud-disk-db
            - POSTGRES_PASSWORD=postgrespassword
        ports: 
            - "5432:5432"
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        ports: 
            - "8000:8000"
        depends_on: 
            - db
        environment: 
            AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
            AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
            AWS_STORAGE_BUCKET_NAME: "${AWS_STORAGE_BUCKET_NAME}"