# Generated by Django 3.0.5 on 2020-04-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_receiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.FileField(upload_to='files/'),
        ),
    ]
